"""Reproduce BSC Q320 factors with rigorous integer intervals and certify all remainders.

Production constants are checked, never written. --write-vectors (or --write)
regenerates only BSC test fixtures. --certify mathematically checks all nonzero
integer-second remainders in a 60-day half-life; it is not an EVM execution test.
No floating-point or transcendental library is used in the proof calculations.
"""
from __future__ import annotations

import argparse
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import platform
import random
import time

ROOT = Path(__file__).resolve().parents[1]
T = 5_184_000
Q256 = 1 << 256
Q320 = 1 << 320
Q512 = 1 << 512
MASK64 = (1 << 64) - 1
CONSTANTS_PATH = ROOT / 'src/libraries/TreasuryDecayConstantsBSC.sol'
DECAY_PATH = ROOT / 'src/libraries/TreasuryDecayBSC.sol'
VECTORS_PATH = ROOT / 'test/fixtures/TreasuryDecayVectorsBSC.sol'
CERTIFICATE_PATH = ROOT / 'artifacts/math-treasury-decay-certificate-bsc.json'


def ceil_div(a: int, b: int) -> int:
    q, r = divmod(a, b)
    return q + (r != 0)


def log_two_interval() -> tuple[int, int]:
    # ln(2) = 2 * sum(k>=0) 1 / ((2k+1)*3**(2k+1)).
    # Floor each of the first 200 positive terms. Rounding loses <200 ulps.
    # The omitted tail is < 9 / (4 * 401 * 3**401), which is < 1 Q512 ulp.
    count = 200
    lower = sum(2 * Q512 // ((2*k + 1) * 3**(2*k + 1)) for k in range(count))
    assert 9 * Q512 < 4 * (2*count + 1) * 3**(2*count + 1)
    return lower, lower + count + 1


LOG_LO, LOG_HI = log_two_interval()


def decay_interval(numerator: int, denominator: int = T) -> tuple[int, int]:
    """Strictly enclosing Q512-scaled exp(-ln(2)*numerator/denominator).

    Inputs here are in (0,1). Bound positive exp(x) with a 128-term Taylor
    expansion and outward integer rounding, then invert the interval.
    The tail after k=128 is < twice the next term because x < 1.
    """
    assert 0 < numerator < denominator
    x_lo = LOG_LO * numerator // denominator
    x_hi = ceil_div(LOG_HI * numerator, denominator)
    assert x_hi < Q512
    term_lo = term_hi = Q512
    sum_lo = sum_hi = Q512
    for k in range(1, 129):
        term_lo = term_lo * x_lo // (Q512 * k)
        term_hi = ceil_div(term_hi * x_hi, Q512 * k)
        sum_lo += term_lo
        sum_hi += term_hi
    sum_hi += 2 * ceil_div(term_hi * x_hi, Q512 * 129)
    return Q512 * Q512 // sum_hi, ceil_div(Q512 * Q512, sum_lo)


def exact_fraction_floor(remainder: int, precision: int) -> int:
    lower, upper = decay_interval(remainder)
    shift = 512 - precision
    lo_floor = lower >> shift
    hi_floor = upper >> shift
    assert lo_floor == hi_floor, (remainder, precision, 'interval ambiguous')
    return lo_floor


FACTORS = [exact_fraction_floor(1 << bit, 320) for bit in range(23)]


def approximate_fraction(remainder: int) -> int:
    # Exactly the Solidity bit order and floor-after-each-product path.
    accumulator = Q320
    bit = 0
    while remainder:
        if remainder & 1:
            accumulator = accumulator * FACTORS[bit] >> 320
        remainder >>= 1
        bit += 1
    return accumulator


def reference_remaining(u0: int, dt: int) -> int:
    assert 0 <= u0 < 1 << 224 and 0 <= dt < 1 << 64
    if u0 == 0 or dt == 0:
        return u0
    if dt >= 224*T:
        return 1
    n, r = divmod(dt, T)
    if r == 0:
        return ceil_div(u0, 1 << n)
    # Evaluate the complete exponent independently, rather than multiplying factors.
    fraction_floor = exact_fraction_floor(r, 256)
    p = (fraction_floor >> n) + 1
    return ceil_div(u0 * p, Q256)


def table_source() -> str:
    entries = '\n'.join(
        f'            case {i} {{\n'
        f'                hi := 0x{c >> 256:016x}\n'
        f'                lo := 0x{c & (Q256-1):064x}\n'
        '            }'
        for i, c in enumerate(FACTORS)
    )
    return '''// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// Generated by scripts/verify_treasury_decay_bsc.py --write; do not hand-edit.
// Every entry is floor(2^320 * 2^(-2^bit / 5184000)), certified by integer intervals.
library TreasuryDecayConstantsBSC {
    function factor(uint256 bit) internal pure returns (uint256 hi, uint256 lo) {
        assembly ("memory-safe") {
            switch bit
''' + entries + '''
        }
    }
}
'''


def vector_source() -> str:
    rng = random.Random(0x574F524C44)
    remainders = sorted(set(
        [1, 2, T//2-1, T//2, T//2+1, T-2, T-1, 3_052_021]
        + [1 << bit for bit in range(23)]
        + [(1 << bit)-1 for bit in range(1, 23)]
        + [rng.randrange(1, T) for _ in range(128)]
    ))
    packed_fractions = b''.join(
        r.to_bytes(3, 'big') + exact_fraction_floor(r, 256).to_bytes(32, 'big')
        for r in remainders
    )
    vectors = []
    for index, r in enumerate(remainders):
        n = [0, 1, 31, 95, 127, 191, 222, 223][index % 8]
        u = [(1 << 224)-1, 1 << 223, (1 << 128)-1, 1, 387 << 96][index % 5]
        dt = n*T+r
        vectors.append((u, dt, reference_remaining(u, dt)))
    packed_remaining = b''.join(
        u.to_bytes(28, 'big') + dt.to_bytes(8, 'big') + expected.to_bytes(28, 'big')
        for u, dt, expected in vectors
    )
    return f'''// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// Independent rational-interval reference vectors; regenerated for BSC with --write-vectors.
library TreasuryDecayVectorsBSC {{
    function fractions() internal pure returns (bytes memory) {{
        return hex"{packed_fractions.hex()}";
    }}

    function remaining() internal pure returns (bytes memory) {{
        return hex"{packed_remaining.hex()}";
    }}
}}
'''


def normalized_source(source: str) -> str:
    # Only serialization and historical generator filename differences are ignored.
    # Solidity identifiers, opcodes, values and all other source text must match.
    return (source.lstrip('\ufeff').replace('\r\n', '\n')
            .replace('scripts/verify_treasury_decay.py', 'scripts/verify_treasury_decay_bsc.py')
            .strip() + '\n')


def reproduce(write_vectors: bool) -> None:
    source = vector_source()
    if write_vectors:
        VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
        VECTORS_PATH.write_text(source, encoding='utf-8', newline='\n')
    else:
        assert normalized_source(VECTORS_PATH.read_text(encoding='utf-8')) == normalized_source(source), (
            f'Generated BSC vectors differ: {VECTORS_PATH}'
        )
    assert normalized_source(CONSTANTS_PATH.read_text(encoding='utf-8')) == normalized_source(table_source()), (
        f'BSC production constants differ from independently generated table: {CONSTANTS_PATH}'
    )
    print('PASS: 23 BSC production constants checked; independent interval vectors reproduced.', flush=True)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def certify() -> None:
    start = time.perf_counter()
    started_at = datetime.now(timezone.utc).isoformat()
    min_margin = 1 << 64
    min_remainder = None
    previous = Q256
    digest = hashlib.sha256()
    for remainder in range(1, T):
        value = approximate_fraction(remainder)
        # Each selected factor incurs <1 factor ulp + <1 product ulp.
        # With <=23 selected bits, true Q320 result is in [value,value+46).
        margin = (1 << 64) - (value & MASK64)
        assert margin >= 46, (remainder, margin, 'Q256 boundary ambiguous')
        exact_floor = value >> 64
        assert exact_floor < previous, ('non-monotone fraction', remainder)
        previous = exact_floor
        digest.update(exact_floor.to_bytes(32, 'big'))
        if margin < min_margin:
            min_margin, min_remainder = margin, remainder
        if remainder % 500_000 == 0:
            print(f'Certified {remainder:,}/{T-1:,} BSC remainders', flush=True)
    assert min_remainder is not None
    independent_floor = exact_fraction_floor(min_remainder, 256)
    assert approximate_fraction(min_remainder) >> 64 == independent_floor
    report = {
        'status': 'PASS',
        'target': 'BSC standalone TreasuryDecayBSC / TreasuryDecayConstantsBSC',
        'verification_kind': 'exhaustive mathematical certification, not EVM execution',
        'method': 'rigorous integer-interval constants; exhaustive Q320 truncation margin',
        'evm_differential_tests': 'separate test suite; not claimed by this certificate',
        'half_life_seconds': T,
        'remainders_checked': T-1,
        'remainder_range_inclusive': [1, T-1],
        'q320_error_strict_upper_bound': 46,
        'minimum_q320_margin_to_next_q256_boundary': min_margin,
        'minimum_margin_remainder_seconds': min_remainder,
        'minimum_margin_independent_q256_floor': str(independent_floor),
        'certified_q256_floors_sha256': digest.hexdigest(),
        'started_at_utc': started_at,
        'completed_at_utc': datetime.now(timezone.utc).isoformat(),
        'elapsed_seconds': round(time.perf_counter()-start, 3),
        'python_version': platform.python_version(),
        'generator_sha256': sha256(Path(__file__)),
        'constants_sha256': sha256(CONSTANTS_PATH),
        'decay_sha256': sha256(DECAY_PATH),
        'vectors_sha256': sha256(VECTORS_PATH),
        'test_sha256': sha256(ROOT / 'test/TreasuryDecayBSC.t.sol'),
        'production_constants_written': False,
        'constants_normalization': 'UTF-8 BOM, CRLF/LF, outer whitespace, historical generator basename only',
    }
    CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
    CERTIFICATE_PATH.write_text(json.dumps(report, indent=2)+'\n', encoding='utf-8', newline='\n')
    print(json.dumps(report, indent=2), flush=True)


if __name__ == '__main__':
    if not __debug__:
        raise SystemExit('Run without Python -O: proof assertions must remain enabled.')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write-vectors', '--write', dest='write_vectors', action='store_true',
                        help='Regenerate BSC fixture only; production constants are never modified.')
    parser.add_argument('--certify', action='store_true', help='Check every nonzero remainder mathematically.')
    args = parser.parse_args()
    reproduce(args.write_vectors)
    if args.certify:
        certify()
