// SPDX-License-Identifier: MIT
pragma solidity 0.8.30;

// Generated by scripts/verify_treasury_decay.py --write; do not hand-edit.
// Every entry is floor(2^320 * 2^(-2^bit / 5184000)), certified by integer intervals.
library TreasuryDecayConstantsBSC {
    function factor(uint256 bit) internal pure returns (uint256 hi, uint256 lo) {
        assembly ("memory-safe") {
            switch bit
            case 0 {
                hi := 0xfffffdc1b977cf86
                lo := 0x60af6bca2ced6418b3c0e6ca052f223cc925156c22cc9c9e057e67cc6b248ab4
            }
            case 1 {
                hi := 0xfffffb8372f4a74d
                lo := 0x1f86fbf0d4ba95c10c78db566e784545b7d12192fb0db46a1d9e87b5e4c5c1ce
            }
            case 2 {
                hi := 0xfffff706e5fd6f9b
                lo := 0x8a86fc64b031a3bd5e62dd6cc2610a21096e147e0ce76c21b72c95e9e6762a57
            }
            case 3 {
                hi := 0xffffee0dcc4b633a
                lo := 0xd9b5a8e870e596cc9d1dea27954b19640f9300d15f956c6e7f0f12ed166122d6
            }
            case 4 {
                hi := 0xffffdc1b99d8d679
                lo := 0x7c275b8688694ce1b49237c2732f82499e88dbae2a184482b398c0bf1e6b3aa5
            }
            case 5 {
                hi := 0xffffb83738b9eca7
                lo := 0xcc2eb1ca0679f4d03a3ed3e3bc301a15e0fd20d3c56141a477ae163b287bf2de
            }
            case 6 {
                hi := 0xffff706e8594d550
                lo := 0x6fb48f64d3a202821b95553fbf81d31ffae9d2885192fd0a9137cb2b92df90db
            }
            case 7 {
                hi := 0xfffee0dd5bad8410
                lo := 0x8109ee6b6fef8a80dc42f8188d9a3a3266fadb537b2edd957b21b7ba15bae9a8
            }
            case 8 {
                hi := 0xfffdc1bbf969b942
                lo := 0x0359907ed0bf7bb5436a54d7748e4bf969221d260ee651734f9f4cb7c69d1547
            }
            case 9 {
                hi := 0xfffb837cfb089221
                lo := 0x6bf0126e17f9d75fb807df32fb5323fee1492cea2373dc67ffba29fc5b4056f9
            }
            case 10 {
                hi := 0xfff7070e16b87bdc
                lo := 0x0e97812aba3eeccdd31979627d6ffb50d92ebe0d971c182cb39128296e2ebfbf
            }
            case 11 {
                hi := 0xffee0e6caea524c3
                lo := 0xfcadcac85be36f368057ca63972f1d7384ef68b60c61af637cac4858b0a16998
            }
            case 12 {
                hi := 0xffdc1e1b56d1cb8c
                lo := 0xb04d6aa33dd2a2575376d71a2b62ec6c555a70b42552e0a9cf91f754235a84da
            }
            case 13 {
                hi := 0xffb8413e397d975c
                lo := 0xba70c9305712f157482372647f07bc610668eee165b7b2c38c86bee5278a2c97
            }
            case 14 {
                hi := 0xff709697d09b8065
                lo := 0xfd54458b8cd3b8ec3114b93bf969c81e31af1f356873fb29fea63452fa568004
            }
            case 15 {
                hi := 0xfee17d868f029459
                lo := 0x83d19892ef227255b779da53df746a413b4b6d4ec82ce3519d5447f0b440727a
            }
            case 16 {
                hi := 0xfdc43bb4e7dd2f4c
                lo := 0xf2643b651bddc43adbf41909cbae68a25e430113a4ca2724f2e05ce55ca70a98
            }
            case 17 {
                hi := 0xfb8d746f0d3b1ce5
                lo := 0x59c62d476d43ded8dce0bc4024258eeae95b7a71884475e9132ab7fce688ccfb
            }
            case 18 {
                hi := 0xf72eb07b3b3b51f1
                lo := 0x9ed177ed03ededc634c911712a10014a3a9b36c9cbca2efcb08d4fe9dffb0107
            }
            case 19 {
                hi := 0xeeab2111b23f6e35
                lo := 0x3caea6c557c039e058887c665b32cd37548771ae8eb6715a975a78ec5181d8dd
            }
            case 20 {
                hi := 0xde82a3e21957a2d5
                lo := 0xbae6711a4706365875f50fcf156b420f10d1dc39a715b1271b9a9502912f077c
            }
            case 21 {
                hi := 0xc166d6e6fe7f6f62
                lo := 0x6bd36761b81f4f1c23660ef36ef6b01772046c571f024222d9f481851361ef1e
            }
            case 22 {
                hi := 0x921c39584035f56a
                lo := 0x81387fedec480de533906524eb2a51672ae29685e1e982e107dd3afb80d0360e
            }
        }
    }
}
