/* Real browser/local-chain tests. Start pnpm run chain:i18n first.
 * PLAYWRIGHT_MODULE may point to an existing Playwright installation.
 * Only localhost unlocked disposable accounts, never public transactions. */
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
process.chdir(path.resolve(__dirname, '..'));
const url = 'http://127.0.0.1:5181', rpcUrl = 'http://127.0.0.1:18575';
const evidence = { kind: 'Real Edge + independent localhost Anvil, no public transactions', cases: [], receipts: [], pageErrors: [] };
const output = 'test-results/i18n-browser.json', images = 'test-results/i18n-screenshots';
fs.mkdirSync(images, { recursive: true });
let browser, page;
const save = () => fs.writeFileSync(output, JSON.stringify(evidence, null, 2) + '\n');
async function test(name, fn) { const start = Date.now(); try { await fn(); evidence.cases.push({ name, status: 'PASS', ms: Date.now()-start }); console.log('PASS', name) } catch(e) { evidence.cases.push({ name, status: 'FAIL', error: e.message }); throw e } finally { save() } }
async function ready() { await page.waitForFunction(() => /(?:Snapshot|快照) #\d+/.test(document.querySelector('.app-footer')?.textContent || '') && !document.querySelector('.map-toolbar .icon-button')?.disabled); }
async function rpc(method, params=[]) { const data=await(await fetch(rpcUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})})).json(); if(data.error) throw Error(data.error.message); return data.result; }
async function tx(button, label) {
  const old = (await page.locator('.notice.status').count()) ? (await page.locator('.notice.status').innerText()).match(/0x[\da-f]{64}/i)?.[0] : undefined;
  await button.click();
  await page.waitForFunction(old => { const s=document.querySelector('.notice.status')?.textContent || '', hash=s.match(/0x[\da-f]{64}/i)?.[0]; return hash && hash!==old && !document.querySelector('.status-dot.loading'); }, old);
  const hash=(await page.locator('.notice.status').innerText()).match(/0x[\da-f]{64}/i)[0], receipt=await rpc('eth_getTransactionReceipt',[hash]);
  assert.equal(receipt.status,'0x1'); evidence.receipts.push({label,hash,status:receipt.status,blockNumber:receipt.blockNumber}); await ready();
}
const button = name => page.getByRole('button', { name, exact:true });
async function switchTo(language) { await button(language==='en'?'EN':'中文').click(); assert.equal(await page.locator('html').getAttribute('lang'),language); }
async function land(id, language='en') { await page.locator('.main-nav').getByRole('button',{name:language==='en'?'World':'世界',exact:true}).click(); await page.getByLabel(language==='en'?'Find LAND':'查找土地').fill(String(id)); await button(language==='en'?'Go to LAND':'前往土地').click(); await page.locator('.land-detail').waitFor(); }
async function capture(name) { await page.screenshot({path:`${images}/${name}.png`,fullPage:!name.startsWith('mobile')}); }
(async()=>{
 const manifest=JSON.parse(fs.readFileSync('work/i18n-local.json','utf8'));
 assert.equal(manifest.rpcUrl,rpcUrl); assert.equal(await rpc('eth_chainId'),'0x7a7f');
 assert.equal(await rpc('evm_revert',[manifest.snapshot]),true);
 manifest.snapshot=await rpc('evm_snapshot');fs.writeFileSync('work/i18n-local.json',JSON.stringify(manifest));
 browser=await chromium.launch({channel:'msedge',headless:true});
 await test('Chinese browser defaults to zh-CN; non-Chinese defaults to en',async()=>{
   for(const locale of ['zh-CN','en-US']) { const c=await browser.newContext({locale}); const p=await c.newPage(); await p.goto(url); await p.getByRole('button',{name:locale==='zh-CN'?'购买 WORLD':'Buy WORLD',exact:true}).waitFor(); assert.equal(await p.locator('html').getAttribute('lang'),locale==='zh-CN'?'zh-CN':'en'); await c.close(); }
 });
 page=await browser.newPage({viewport:{width:1440,height:1040},locale:'en-US'});page.setDefaultTimeout(25000);page.on('dialog',d=>d.accept());page.on('pageerror',e=>evidence.pageErrors.push(e.message));
 await test('English world renders all 50 real LAND with no untranslated system Chinese',async()=>{ await page.goto(url+'/?lang=en&campaign=copy-review#world'); await ready(); assert.equal(await page.locator('[data-land-id]').count(),50); const text=await page.locator('body').innerText(); assert.ok(!/[\p{Script=Han}]/u.test(text.replaceAll('中文',''))); await capture('desktop-en'); });
 await test('manual switch updates UI and toolbar, preserves query/hash, and persists on reload',async()=>{ await switchTo('zh-CN'); assert.match(page.url(),/campaign=copy-review/);assert.match(page.url(),/#world/);await button('本地 +45天').waitFor(); await capture('desktop-zh'); await page.goto(url+'/?campaign=copy-review'); await ready(); assert.equal(await page.locator('html').getAttribute('lang'),'zh-CN'); await page.goto(url+'/?lang=en&campaign=copy-review');await ready();assert.equal(await page.locator('html').getAttribute('lang'),'en'); });
 await test('disconnected Wallet gate and translated Buy quote',async()=>{ await button('Buy WORLD').click(); await page.locator('#buy-amount').fill('10000'); await page.getByRole('dialog').getByText('Connect Wallet to Play',{exact:true}).waitFor(); await button('Close Action').click(); await button('Connect Wallet').click(); await page.locator('.wallet-connected').waitFor();await ready(); });
 await test('English Buy mints and keeps amount unchanged',async()=>{await button('Buy WORLD').click();await page.locator('#buy-amount').fill('10000');await page.waitForFunction(()=>!document.querySelector('.transaction-modal .button.primary')?.disabled);await tx(page.getByRole('dialog').getByRole('button',{name:'Buy WORLD',exact:true}),'en buy 10000');assert.match(await page.locator('.notice.status').innerText(),/Minted in full/);await button('Close Action').click();});
 await test('English approval + Attack conquers with real receipt',async()=>{await land(1);await page.locator('#war-amount').fill('100');await tx(button('1 · Approve This WORLD Amount'),'en approve 100');await tx(button('Burn · Submit Attack'),'en attack 100');assert.match(await page.locator('.notice.status').innerText(),/conquered/);});
 await test('English Defend burns and reinforces, Chinese cached toast changes without new action',async()=>{await page.getByRole('tab',{name:'Defend',exact:true}).click();await page.locator('#war-amount').fill('25');await tx(button('1 · Approve This WORLD Amount'),'en approve 25');await tx(button('Burn · Confirm Defense'),'en defend 25');assert.match(await page.locator('.notice.status').innerText(),/Resistance increased/);const n=evidence.receipts.length;await switchTo('zh-CN');assert.match(await page.locator('.notice.status').innerText(),/Resistance已增加/);assert.equal(evidence.receipts.length,n);});
 await test('Chinese Buy and Defend are playable',async()=>{await button('关闭土地详情').click();await button('购买 WORLD').click();await page.locator('#buy-amount').fill('1000');await page.waitForFunction(()=>!document.querySelector('.transaction-modal .button.primary')?.disabled);await tx(page.getByRole('dialog').getByRole('button',{name:'购买 WORLD',exact:true}),'zh buy 1000');await button('关闭操作').click();await land(1,'zh-CN');await page.getByRole('tab',{name:'补防',exact:true}).click();await page.locator('#war-amount').fill('5');await tx(button('1 · 授权本次 WORLD'),'zh approve 5');await tx(button('Burn · 确认补防'),'zh defend 5');});
 await test('Chinese Profile remains unchanged across languages',async()=>{await page.getByRole('tab',{name:'土地名称',exact:true}).click();await page.locator('#profile-name').fill('玩家中文 PEPE');await tx(button('保存'),'profile');await switchTo('en');assert.equal(await page.locator('.land-detail h2').innerText(),'玩家中文 PEPE');assert.equal(await page.locator('#profile-name').inputValue(),'玩家中文 PEPE');await capture('desktop-en-profile');});
 await test('Claim settles before separate Withdrawal in English',async()=>{await button('Close LAND Details').click();await rpc('evm_increaseTime',[86400]);await rpc('evm_mine');await button('Refresh World').click();await ready();await page.locator('.main-nav').getByRole('button',{name:'My World',exact:true}).click();await button('Settle & Withdraw').click();await tx(page.locator('.settlement-list').getByRole('button',{name:'Settle',exact:true}),'en settle');await tx(button('Withdraw Settled BNB'),'en withdraw');await button('Close Action').click();});
 await test('Return Leaderboard has no category tabs or History navigation',async()=>{assert.equal(await page.locator('.main-nav').getByRole('button',{name:'History',exact:true}).count(),0);await page.locator('.main-nav').getByRole('button',{name:'Leaderboard',exact:true}).click();assert.equal(await page.locator('.ranking-categories').count(),0);assert.equal(await page.locator('#leaderboard-title').innerText(),'RETURN LEADERBOARD');await capture('desktop-en-leaderboard');});
 await test('wrong injected Wallet network disables writes with translated warning',async()=>{await page.evaluate(()=>{window.__request=window.ethereum.request.bind(window.ethereum);window.ethereum.request=a=>a.method==='eth_chainId'?Promise.resolve('0x38'):window.__request(a)});await page.getByLabel('Local Test Account',{exact:true}).selectOption('1');await page.locator('.notice.warning').waitFor();await land(1);assert.equal(await button('Burn · Submit Attack').isDisabled(),true);assert.match(await page.locator('.notice.warning').innerText(),/different network/);await page.evaluate(()=>window.ethereum.request=window.__request);await button('Close LAND Details').click();await page.getByLabel('Local Test Account',{exact:true}).selectOption('0');await ready();});
 await test('RPC failure uses friendly English and Chinese; Retry recovers',async()=>{await page.route(rpcUrl+'/**',r=>r.abort());await page.route(rpcUrl,r=>r.abort());await button('Refresh World').click();await page.locator('.notice.error').waitFor();assert.match(await page.locator('.notice.error').innerText(),/RPC/);await switchTo('zh-CN');assert.match(await page.locator('.notice.error').innerText(),/RPC/);await page.unroute(rpcUrl);await page.unroute(rpcUrl+'/**');await page.locator('.notice.error').getByRole('button',{name:'重试',exact:true}).click();await ready();});
 await test('Mobile English and Chinese controls remain usable with no horizontal overflow',async()=>{await page.setViewportSize({width:390,height:844});for(const lang of ['en','zh-CN']){await switchTo(lang);await land(1,lang);await page.locator('#war-amount').fill('1');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.locator('.land-detail').evaluate(el=>el.scrollTop=0);await capture('mobile-'+lang+'-land');await button(lang==='en'?'Close LAND Details':'关闭土地详情').click();await capture('mobile-'+lang+'-world');}});
 assert.equal(evidence.pageErrors.length,0);evidence.summary={passed:evidence.cases.length,failed:0,realLocalTransactions:evidence.receipts.length};save();console.log(JSON.stringify(evidence.summary));
})().catch(async e=>{evidence.failure=e.message;save();console.error(e.message);if(page){console.error((await page.locator('body').innerText()).slice(-3500));await page.screenshot({path:'work/i18n-browser-debug.png',fullPage:true}).catch(()=>{})}process.exitCode=1}).finally(async()=>{await browser?.close()});
