/* Local browser tests against the actual Vite UI + unlocked localhost Anvil.
 * No private key. Requires a fresh `chain:local` world and the dev server.
 * Set PLAYWRIGHT_MODULE to the path of your existing Playwright installation.
 */
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'..'); process.chdir(root);
const evidence={started:new Date().toISOString(),kind:'Real Edge browser + localhost unlocked test wallet, no public network',cases:[],transactions:[],consoleErrors:[]};
const manifest=JSON.parse(fs.readFileSync('test-results/local-deployment-v2.json'));
const rpcUrl=manifest.rpcUrl; if(manifest.chainId!==31359||new URL(rpcUrl).hostname!=='127.0.0.1')throw Error('Local test only');
let browser,page,rejectNext=false;const observed=[];
async function rpc(method,params=[]){const d=await(await fetch(rpcUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})})).json();if(d.error)throw Error(d.error.message);return d.result}
const save=()=>fs.writeFileSync('test-results/browser-e2e-v2.json',JSON.stringify(evidence,null,2)+'\n');
async function test(name,fn){const began=Date.now();try{await fn();evidence.cases.push({name,status:'PASS',durationMs:Date.now()-began});console.log('PASS',name)}catch(e){evidence.cases.push({name,status:'FAIL',error:e.message,durationMs:Date.now()-began});throw e}finally{save()}}
async function ready(){await page.waitForFunction(()=>/快照 #\d+/.test(document.querySelector('.app-footer')?.textContent||''));await page.waitForFunction(()=>!document.querySelector('[aria-label="刷新世界"]')?.disabled);}
async function tx(button,label){const oldHash=(await page.locator('.notice.status').count())?(await page.locator('.notice.status').innerText()).match(/0x[0-9a-f]{64}/i)?.[0]:undefined;await button.click();await page.waitForFunction(old=>{const t=document.querySelector('.notice.status')?.textContent||'',hash=t.match(/0x[0-9a-f]{64}/i)?.[0];return !document.querySelector('.status-dot.loading')&&hash&&hash!==old},oldHash,{timeout:30000});const hash=(await page.locator('.notice.status').innerText()).match(/0x[0-9a-f]{64}/i)[0];const receipt=await rpc('eth_getTransactionReceipt',[hash]);assert.equal(receipt.status,'0x1');evidence.transactions.push({label,hash,receipt});await ready();save();}
async function connect(){await page.getByRole('button',{name:'连接钱包',exact:true}).click();await page.waitForSelector('.wallet-connected');await ready();}
async function world(){await page.locator('.main-nav').getByRole('button',{name:'世界',exact:true}).click();await ready();}
async function land(id){await world();await page.getByLabel('查找土地').fill(String(id));await page.getByRole('button',{name:'前往土地'}).click();await page.waitForSelector(`[aria-label="LAND #${id} 详情"]`);}
const detail=()=>page.locator('.land-detail');
async function buy(amount){await world();await page.locator('.world-heading-actions').getByRole('button',{name:'购买 WORLD'}).click();await page.locator('#buy-amount').fill(amount);const b=page.getByRole('dialog').getByRole('button',{name:'购买 WORLD'});await b.waitFor();await page.waitForFunction(()=>!document.querySelector('.transaction-modal .button.primary')?.disabled);await tx(b,'buy '+amount);assert.match(await page.locator('.notice.status').innerText(),/全量 mint/);await page.getByRole('button',{name:'关闭操作'}).click();}
async function war(mode,amount){await detail().getByRole('tab',{name:mode==='attack'?'攻击':'补防',exact:true}).click();await page.locator('#war-amount').fill(amount);const approve=detail().getByRole('button',{name:'1 · 授权本次 WORLD',exact:true});if(await approve.count())await tx(approve,'approve exact '+amount);await tx(detail().getByRole('button',{name:mode==='attack'?'Burn · 提交攻击':'Burn · 确认补防',exact:true}),mode+' '+amount);}
async function advance(days){await page.getByRole('button',{name:`本地 +${days}天`,exact:true}).click();await page.waitForSelector('.wallet-connected',{state:'detached'});await connect();}
async function account(index){await page.getByLabel('本地测试账户',{exact:true}).selectOption(String(index));await ready();await page.waitForTimeout(250);}
async function capture(name){await page.screenshot({path:`test-results/screenshots/${name}.png`,fullPage:true});}
(async()=>{
 fs.mkdirSync('test-results/screenshots',{recursive:true});
 browser=await chromium.launch({channel:'msedge',headless:true});page=await browser.newPage({viewport:{width:1440,height:1040}});page.setDefaultTimeout(20000);
 page.on('pageerror',e=>evidence.consoleErrors.push(e.message));
 page.on('dialog',async d=>{if(rejectNext){rejectNext=false;await d.dismiss()}else await d.accept()});
 page.on('response',async response=>{try{const request=response.request(),data=request.postDataJSON();if(request.url().replace(/\/$/,'')===rpcUrl.replace(/\/$/,'')&&data?.method==='eth_sendTransaction'){const result=await response.json();if(result.result)observed.push(result.result)}}catch{}});
 await test('startup reads real factory and renders 50 fixed lands',async()=>{await page.goto('http://127.0.0.1:5179');await ready();assert.equal(await page.locator('[data-land-id]').count(),50);assert.match(await page.locator('.global-metrics').innerText(),/WORLD · 当前供应/);await connect();});
 await test('all 50 SVG lands keyboard-select, zoom and reset work',async()=>{for(let id=1;id<=50;id++){await page.locator(`[data-land-id="${id}"]`).focus();await page.keyboard.press('Enter');await page.waitForSelector(`[aria-label="LAND #${id} 详情"]`)}await page.getByRole('button',{name:'关闭土地详情'}).click();await page.getByRole('button',{name:'放大地图',exact:true}).click();assert.match(await page.locator('.wm-view-controls').innerText(),/130%/);await page.getByRole('button',{name:'复位地图',exact:true}).click();assert.match(await page.locator('.wm-view-controls').innerText(),/100%/);});
 await test('buy form pays actual BNB and mints WORLD',async()=>{await buy('10000')});
 await test('wallet rejection submits no transaction or Burn',async()=>{await land(1);const count=observed.length;rejectNext=true;await detail().getByRole('button',{name:'1 · 授权本次 WORLD',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.notice.error')?.textContent?.includes('取消'));assert.equal(observed.length,count);});
 await test('exact approval then Attack burns and takes neutral Crown',async()=>{await war('attack','100');assert.match(await page.locator('.notice.status').innerText(),/严格跨线/);assert.match(await detail().innerText(),/YOUR LAND/);});
 await test('fresh invalid Profile can edit; UTF8 limit blocks excess',async()=>{await detail().getByRole('tab',{name:'土地名称',exact:true}).click();await page.locator('#profile-name').fill('界'.repeat(100));assert.equal(await detail().getByRole('button',{name:'保存'}).isDisabled(),true);await page.locator('#profile-name').fill('燃烧王座');await tx(detail().getByRole('button',{name:'保存'}),'profile first');assert.equal(await detail().locator('h2').innerText(),'燃烧王座');});
 await test('Profile name clearing and replacement use actual transactions',async()=>{await page.locator('#profile-name').fill('');await tx(detail().getByRole('button',{name:'保存'}),'profile clear');assert.equal(await detail().locator('h2').innerText(),'LAND #1');await page.locator('#profile-name').fill('燃烧王座');await tx(detail().getByRole('button',{name:'保存'}),'profile replace');});
 await test('Defend burns full amount and increases Resistance',async()=>{await war('defend','25');assert.match(await page.locator('.notice.status').innerText(),/Resistance已增加/);});
 await test('local 45-day control advances real chain without auto takeover',async()=>{await advance(45);await land(1);assert.match(await detail().innerText(),/YOUR LAND/);const resistance=await detail().locator('.resistance-numbers').innerText();assert.match(resistance,/62\./);});
 await test('wallet switch clears old UI plans; B buys and takes A land',async()=>{await account(1);assert.equal(await detail().count(),0);await buy('10000');await land(1);await war('attack','200');assert.match(await page.locator('.notice.status').innerText(),/严格跨线/);assert.equal(await detail().locator('h2').innerText(),'LAND #1');await capture('desktop-land-takeover');});
 await test('old owner with no land can withdraw retained Claim',async()=>{await account(0);await page.locator('.main-nav').getByRole('button',{name:'我的世界',exact:true}).click();await page.getByRole('button',{name:'结算与提款',exact:true}).click();assert.equal(await page.locator('.settlement-list').count(),0);await tx(page.getByRole('button',{name:'提取已结算 BNB',exact:true}),'old owner withdraw');await capture('desktop-old-owner-claim');await page.getByRole('button',{name:'关闭操作'}).click();});
 await test('60-day release; current owner settles then withdraws separately',async()=>{await advance(60);await account(1);await page.locator('.main-nav').getByRole('button',{name:'我的世界',exact:true}).click();await page.getByRole('button',{name:'结算与提款',exact:true}).click();await tx(page.locator('.settlement-list').getByRole('button',{name:'结算',exact:true}),'current owner settle');await tx(page.getByRole('button',{name:'提取已结算 BNB',exact:true}),'current owner withdraw');await page.getByRole('button',{name:'关闭操作'}).click();});
 await test('new owner Profile and self-attack epoch invalidate old Profile',async()=>{await land(1);await detail().getByRole('tab',{name:'土地名称',exact:true}).click();await page.locator('#profile-name').fill('第二王朝');await tx(detail().getByRole('button',{name:'保存'}),'new owner profile');await war('attack','300');assert.equal(await detail().locator('h2').innerText(),'LAND #1');assert.match(await detail().innerText(),/YOUR LAND/);});
 await test('negative/overprecision and insufficient WORLD disable war',async()=>{await page.locator('#war-amount').fill('0.0000000000000000001');assert.equal(await detail().getByRole('button',{name:'Burn · 提交攻击',exact:true}).isDisabled(),true);await page.locator('#war-amount').fill('1000000000');assert.match(await detail().innerText(),/WORLD余额不足/);assert.equal(await detail().getByRole('button',{name:'Burn · 提交攻击',exact:true}).isDisabled(),true);await page.locator('#war-amount').fill('1');});
 await test('RPC failure removes financial values and recovers by retry',async()=>{await world();await page.route(rpcUrl,route=>route.abort('connectionfailed'));await page.getByRole('button',{name:'刷新世界',exact:true}).click();await page.waitForFunction(()=>!!document.querySelector('.notice.error'));assert.match(await page.locator('.global-metrics').innerText(),/—/);assert.equal(await page.locator('.live-indicator .online').count(),0);await page.unroute(rpcUrl);await page.locator('.notice.error').getByRole('button',{name:'重试',exact:true}).click();await ready();});
 await test('desktop map and live profile screenshot',async()=>{await land(1);await detail().getByRole('tab',{name:'土地名称',exact:true}).click();await page.locator('#profile-name').fill('燃烧王座 · V2');await tx(detail().getByRole('button',{name:'保存'}),'final playable profile');await detail().getByRole('tab',{name:'攻击',exact:true}).click();await capture('desktop-world-v2');await page.getByRole('button',{name:'关闭土地详情'}).click();await capture('desktop-map-v2');});
 await test('mobile 390px map, selection and scrollable bottom panel',async()=>{await page.setViewportSize({width:390,height:844});await world();await page.evaluate(()=>window.scrollTo(0,0));assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await capture('mobile-map-v2');await land(1);const box=await detail().boundingBox();assert.ok(box&&box.width<=390&&box.x>=0);await page.locator('#war-amount').scrollIntoViewIfNeeded();await page.locator('#war-amount').fill('1');assert.ok(await page.locator('#war-amount').isVisible());await capture('mobile-attack-v2');await detail().getByRole('tab',{name:'土地名称',exact:true}).click();await page.locator('#profile-name').scrollIntoViewIfNeeded();await capture('mobile-profile-v2');await page.getByRole('button',{name:'关闭土地详情'}).click();});
 assert.equal(evidence.consoleErrors.length,0);evidence.completed=new Date().toISOString();evidence.summary={passed:evidence.cases.filter(x=>x.status==='PASS').length,failed:0,realUiTransactions:evidence.transactions.length};save();console.log(JSON.stringify(evidence.summary));
})().catch(async e=>{console.error(e);evidence.fatal=e.stack;save();if(page){await page.screenshot({path:'test-results/browser-failure.png',fullPage:true}).catch(()=>{});console.error((await page.locator('body').innerText()).slice(-6000))}process.exitCode=1}).finally(async()=>{await browser?.close()});
