import fs from 'node:fs'
import path from 'node:path'
import { createWalletClient, http, parseUnits } from 'viem'
import { mnemonicToAccount } from 'viem/accounts'
import { createWorldReader, executeWorldAction, type WorldAction } from '../src/chain'
import { LOCAL_MNEMONIC } from './anvil'
import { projectRoot } from './compile.mjs'

// Optional real-transaction fixture for a running disposable local chain.
// No state is injected into the DApp, and no public-network endpoint is accepted.
const content = fs.readFileSync(path.join(projectRoot, '.env.local'), 'utf8')
if (!content.startsWith('# WORLD_BSC_V2_LOCAL_MANAGED: disposable local Anvil deployment')) {
  throw new Error('Seed requires the .env.local generated by chain:local')
}
const env = Object.fromEntries(content.split(/\r?\n/).filter(line => line && !line.startsWith('#')).map(line => {
  const split = line.indexOf('=')
  return [line.slice(0, split), line.slice(split + 1)]
}))
const rpcUrl = env.VITE_RPC_URL
if (env.VITE_CHAIN_ID !== '31359' || !/^http:\/\/127\.0\.0\.1:\d+$/.test(rpcUrl)) {
  throw new Error('Seed supports only WORLD local chain 31359 at 127.0.0.1')
}
const reader = createWorldReader({
  chainId: 31359, rpcUrl, nativeSymbol: 'BNB',
  deploymentAddress: env.VITE_DEPLOYMENT_ADDRESS as `0x${string}`,
  deploymentBlock: BigInt(env.VITE_DEPLOYMENT_BLOCK), recentBlockWindow: 5000n,
})
if (await reader.publicClient.getChainId() !== 31359) throw new Error('Local chain ID mismatch')
const initial = await reader.readSnapshot()
if (initial.totalSupply !== 0n || initial.lands.some(land => land.epoch !== 0n)) {
  throw new Error('Seed refuses to modify an already used world. Start a fresh disposable local chain first.')
}
const wallets = [0, 1, 2].map(addressIndex => {
  const account = mnemonicToAccount(LOCAL_MNEMONIC, { addressIndex })
  return createWalletClient({ account, chain: reader.publicClient.chain, transport: http(rpcUrl) })
})
const transactions: unknown[] = []
async function act(index: number, action: WorldAction) {
  const wallet = wallets[index]
  const receipt = await executeWorldAction(reader, wallet, wallet.account.address, action)
  transactions.push({ from: wallet.account.address, action, hash: receipt.transactionHash, block: receipt.blockNumber })
}
async function attack(index: number, id: number, amount: string) {
  const land = await reader.readLand(id)
  await act(index, { kind: 'attack', id, amount: parseUnits(amount, 18), expectedEpoch: land.epoch, expectedResistanceRaw: land.resistanceRaw, expectedLastResistanceUpdate: land.lastResistanceUpdate })
}
for (const index of [0, 1, 2]) {
  const amount = parseUnits('1000', 18)
  await act(index, { kind: 'buy', amount, quotedCost: await reader.quoteBuy(amount) })
  await act(index, { kind: 'approve', amount })
}
for (const [index, id, amount] of [[0, 1, '180'], [0, 2, '80'], [0, 7, '45'], [0, 10, '65'], [1, 3, '120'], [1, 8, '55'], [1, 12, '35'], [2, 4, '75'], [2, 20, '90']] as const) {
  await attack(index, id, amount)
}
await attack(1, 1, '60')
await attack(1, 2, '20')
await attack(2, 7, '55')
for (const [index, id, name] of [[0, 1, 'WORLD 王冠'], [0, 2, '北境同盟'], [1, 3, '赤砂港'], [2, 4, '翡翠高地'], [2, 7, '新纪元'], [1, 12, '旅人营地']] as const) {
  const land = await reader.readLand(id)
  await act(index, { kind: 'profile', id, expectedEpoch: land.epoch, name })
}
await reader.publicClient.request({ method: 'evm_increaseTime' as never, params: [7 * 86_400] as never })
await reader.publicClient.request({ method: 'evm_mine' as never } as never)
await act(0, { kind: 'settle', id: 1 })
const final = await reader.readSnapshot(wallets[0].account.address)
fs.mkdirSync(path.join(projectRoot, 'test-results'), { recursive: true })
fs.writeFileSync(path.join(projectRoot, 'test-results/local-seed-v2.json'), JSON.stringify({
  localOnly: true, executedAt: new Date().toISOString(), rpcUrl, chainId: 31359,
  explanation: 'Optional local testing fixture: actual purchases/approvals/attacks/Profile edits and settlement; local EVM time advanced by 7 days. No public BSC transaction.',
  wallets: wallets.map(wallet => wallet.account.address), transactions,
  finalBlock: final.blockNumber, occupiedLands: final.lands.filter(land => land.epoch !== 0n).map(land => land.id),
}, (_, value) => typeof value === 'bigint' ? value.toString() : value, 2) + '\n')
console.log(`Seeded ${transactions.length} real local transactions; nine occupied LAND and seven days of local EVM time. Public BSC was not used.`)
