const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright')
const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const base = process.env.WHITEPAPER_BASE_URL || 'http://127.0.0.1:4188'
const output = path.resolve(__dirname, '../test-results/whitepaper')
fs.mkdirSync(output, { recursive: true })

;(async () => {
  const browser = await chromium.launch({ channel: 'msedge', headless: true })
  const results = []
  try {
    for (const [name, width, height] of [['desktop', 1440, 960], ['mobile', 390, 844]]) {
      const context = await browser.newContext({ viewport: { width, height }, locale: 'zh-CN' })
      const page = await context.newPage()
      const errors = [], chainReads = []
      page.on('pageerror', error => errors.push(error.message))
      page.on('request', request => {
        const url = new URL(request.url())
        if (url.pathname === '/rpc' || url.pathname.startsWith('/api/')) chainReads.push(url.pathname)
        assert(!/nodereal\.io|onfinality\.io/.test(url.hostname), 'Upstream must not be visible to browser')
      })
      const response = await page.goto(`${base}/whitepaper?lang=zh-CN`, { waitUntil: 'networkidle' })
      assert.equal(response.status(), 200)
      await page.locator('.whitepaper-content h1').waitFor()
      assert.equal(await page.locator('.whitepaper-content h1').innerText(), 'WORLD')
      assert.equal(await page.locator('html').getAttribute('lang'), 'en')
      assert.equal(await page.locator('.whitepaper-content table').count(), 7)
      assert.equal(await page.locator('.katex-display').count(), 5)
      assert.equal(await page.locator('.whitepaper-content .katex-error').count(), 0)
      assert.equal(await page.getByRole('link', { name: 'View source on GitHub' }).getAttribute('href'), 'https://github.com/burn-the-world/world-public/blob/main/docs/WHITEPAPER.md')
      assert.deepEqual(chainReads, [], 'Whitepaper must not load WORLD state or wallet reads')
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'No page-level horizontal overflow')
      const documentLinks = await page.locator('.whitepaper-content a').evaluateAll(nodes => nodes.map(node => node.getAttribute('href')))
      assert(documentLinks.every(href => href.startsWith('https://') || href.startsWith('#')), 'Document links must resolve on the public site')
      await page.screenshot({ path: path.join(output, `${name}-whitepaper.png`) })
      await page.locator('.katex-display').first().scrollIntoViewIfNeeded()
      await page.screenshot({ path: path.join(output, `${name}-equations.png`) })
      await page.goto(`${base}/whitepaper/#appendix-b-contract-addresses`, { waitUntil: 'networkidle' })
      await page.locator('.whitepaper-content h1').waitFor()
      assert.equal(await page.locator('.whitepaper-content table').count(), 7, 'Trailing-slash deep links render')
      await page.goto(`${base}/?lang=en`, { waitUntil: 'domcontentloaded' })
      await page.locator('.app-footer button').click()
      await page.evaluate(() => scrollTo(0, 0))
      assert.equal(await page.locator('.doc-card').count(), 3)
      const cards = await page.locator('.doc-card').evaluateAll(nodes => nodes.map(node => ({ x: node.getBoundingClientRect().x, y: node.getBoundingClientRect().y, href: node.getAttribute('href') })))
      assert(cards.some(card => card.href === './docs/V2_UI_RULES.md'))
      assert(cards.some(card => card.href === './docs/V2_CONTRACT_INTEGRATION.md'))
      if (name === 'mobile') assert(cards[0].y < cards[1].y && cards[1].y < cards[2].y)
      else assert.equal(cards[0].y, cards[2].y)
      await page.screenshot({ path: path.join(output, `${name}-docs.png`) })
      await page.locator('a.doc-card[href="/whitepaper"]').click()
      await page.locator('.whitepaper-content h1').waitFor()
      await page.reload({ waitUntil: 'networkidle' })
      assert.equal(await page.locator('.whitepaper-content h1').innerText(), 'WORLD')
      assert.deepEqual(errors, [])
      results.push({ viewport: name, status: 'PASS', whitepaperChainReads: 0, tables: 7, equations: 5, docsCards: 3 })
      await context.close()
    }
    fs.writeFileSync(path.join(output, 'results.json'), JSON.stringify({ base, results }, null, 2) + '\n')
    console.log(JSON.stringify({ base, results }))
  } finally { await browser.close() }
})().catch(error => { console.error(error.message); process.exitCode = 1 })
